lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/Linkedin_AP_NC_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is used to store information about the Auth Provider and Named Credentials for Linked In Manager for each user.</description>
    <label>Linkedin AP NC Setting</label>
    <pluralLabel>Linkedin AP NC Settings</pluralLabel>
</CustomObject>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/AP_Created__c.field-meta.xml
<CustomField>
    <fullName>AP_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP Created</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/AP_Name__c.field-meta.xml
<CustomField>
    <fullName>AP_Name__c</fullName>
    <label>AP Name</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>This field is used to store the client id of the linked in client app.</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>This field is used to store the client secret for the linked-in client app.</description>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/Marketing_Developer_Product__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Developer_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Developer Product</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/NC_Authenticated__c.field-meta.xml
<CustomField>
    <fullName>NC_Authenticated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NC Authenticated</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/NC_Created__c.field-meta.xml
<CustomField>
    <fullName>NC_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NC Created</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/NC_Name__c.field-meta.xml
<CustomField>
    <fullName>NC_Name__c</fullName>
    <label>NC Name</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/Share_On_Product__c.field-meta.xml
<CustomField>
    <fullName>Share_On_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Share On Product</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/Sign_In_Product__c.field-meta.xml
<CustomField>
    <fullName>Sign_In_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign In Product</label>
    <type>Checkbox</type>
</CustomField>

lim-project/force-app/main/default/objects/Linkedin_AP_NC_Setting__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <defaultValue>$User.Id</defaultValue>
    <description>This field stores the user id of the user for which the record is saved.</description>
    <label>User Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lim-project/force-app/main/default/classes/LinkedinApNcSettingHelper.cls
/**
 * @description       : This helper class communicates with the Linkedin AP NC Setting Metadata
 * @author            : Amit Kumar [amitniitmca@gmail.com]
 * @last modified on  : 15-02-2022
 * @last modified by  : Amit Kumar [amitniitmca@gmail.com]
 **/
public inherited sharing class LinkedinApNcSettingHelper{
    private static final String NAMESPACE = 'liman__';
    private static final String OBJECT_NAME = 'Linkedin_AP_NC_Setting__mdt';
    private static final List<String> FIELDS = new List<String>{ NAMESPACE + 'AP_Created__c', NAMESPACE + 'AP_Name__c', NAMESPACE + 'Client_Id__c', NAMESPACE + 'Client_Secret__c', NAMESPACE + 'Marketing_Developer_Product__c', NAMESPACE + 'NC_Authenticated__c', NAMESPACE + 'NC_Created__c', NAMESPACE + 'NC_Name__c', NAMESPACE + 'Share_On_Product__c', NAMESPACE + 'Sign_In_Product__c', NAMESPACE + 'User_Id__c'};

    // public void createRecord(String developerName, )
}